#!/usr/bin/env python

import pandas as pd
import sys
from decimal import Decimal

data = pd.read_csv(sys.argv[1])
mu = data.mu.mean()
sigma = data.sigma.mean()
print("mu: {0} \nsigma: {1}".format(mu, sigma))

